#!/bin/sh

#### PBS preamble

#PBS -N NRD_hypertune4

#PBS -M wsliu@umich.edu
#PBS -m abe

#PBS -A awaljee_fluxod

#PBS -q fluxod

#PBS -V
#PBS -l nodes=1:ppn=2,pmem=16gb,walltime=8:00:00
#PBS -j oe

#### End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Put your job commands here:
sh hypertune4.sh