python train_template_xgboost0425.py --lr 2e-05 --tst_seed 0 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 1 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 2 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 3 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 4 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 5 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 6 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 7 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 8 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
python train_template_xgboost0425.py --lr 2e-05 --tst_seed 9 --cohort chf --folder multi_space_glove/ --dx_rarecutpoint 10 --pr_rarecutpoint 10 --result_file output/ht_result0524_{}.csv --job_index 1
