qsub batch0.pbs
qsub batch1.pbs
qsub batch2.pbs
qsub batch3.pbs
qsub batch4.pbs
qsub batch5.pbs
qsub batch6.pbs
qsub batch7.pbs
qsub batch8.pbs
qsub batch9.pbs
qsub batch10.pbs
#qsub batch11.pbs
#qsub batch12.pbs