#qsub batch_gpu0.pbs
qsub batch_gpu1.pbs
qsub batch_gpu2.pbs
qsub batch_gpu3.pbs
qsub batch_gpu4.pbs
qsub batch_gpu5.pbs
qsub batch_gpu6.pbs
#qsub batch_gpu7.pbs
#qsub batch_gpu8.pbs
#qsub batch_gpu9.pbs
#qsub batch_gpu10.pbs
#qsub batch_gpu11.pbs
