#!/bin/sh

#### PBS preamble

#PBS -N colonoscopy_3binary_cv5

#PBS -M wsliu@umich.edu
#PBS -m abe

#PBS -A bnallamo_armisg

#PBS -q armisg

#PBS -V
#PBS -l nodes=1:gpus=1,mem=8gb,walltime=48:00:00
#PBS -j oe

#### End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Put your job commands here:
python phase2_3binary5.py 
